### ISSUE TITLE
zlib error when authenticating from the player

### ISSUE THREAD

**Issue by Montellese** [Montellese/mediaimporter.emby#18]
Sometimes the `urllib3` library used by the `requests` library throws a `zlib` error when trying to authenticate:
```
Error Type: <class 'zlib.error'>
         Error Contents: Error -3 while decompressing data: incorrect header check
         Traceback (most recent call last):
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\addons\mediaimporter.emby\emby\player.py", line 83, in onAVStarted
             self._startPlayback()
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\addons\mediaimporter.emby\emby\player.py", line 186, in _startPlayback
             if not self._server or not self._server.Authenticate(force=True):
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\addons\mediaimporter.emby\emby\server.py", line 55, in Authenticate
             return self._authenticate(force=force)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\addons\mediaimporter.emby\emby\server.py", line 321, in _authenticate
             if not self._authenticator.Authenticate(force=force):
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\addons\mediaimporter.emby\emby\authenticator.py", line 41, in Authenticate
             authResult = self._authenticate()
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\addons\mediaimporter.emby\emby\authenticator.py", line 103, in _authenticate
             deviceId=self._deviceId)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\addons\mediaimporter.emby\emby\api\authentication.py", line 57, in Authenticate
             resultObj = Request.PostAsJson(authUrl, headers=headers, json=body, timeout=Authentication.REQUEST_TIMEOUT_S)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\addons\mediaimporter.emby\emby\request.py", line 77, in PostAsJson
             result = Request._post(url, headers=headers, body=body, json=json, timeout=timeout)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\addons\mediaimporter.emby\emby\request.py", line 107, in _post
             return requests.post(url, headers=headers, timeout=timeout, data=body, json=json, verify=False)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.requests\lib\requests\api.py", line 116, in post
             return request('post', url, data=data, json=json, **kwargs)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.requests\lib\requests\api.py", line 60, in request
             return session.request(method=method, url=url, **kwargs)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.requests\lib\requests\sessions.py", line 533, in request
             resp = self.send(prep, **send_kwargs)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.requests\lib\requests\sessions.py", line 686, in send
             r.content
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.requests\lib\requests\models.py", line 828, in content
             self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.requests\lib\requests\models.py", line 750, in generate
             for chunk in self.raw.stream(chunk_size, decode_content=True):
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.urllib3\lib\urllib3\response.py", line 564, in stream
             data = self.read(amt=amt, decode_content=decode_content)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.urllib3\lib\urllib3\response.py", line 536, in read
             data = self._decode(data, decode_content, flush_decoder)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.urllib3\lib\urllib3\response.py", line 388, in _decode
             data = self._decoder.decompress(data)
           File "D:\Coding\Cpp\xbmc.montellese\kodi-build.win10\portable_data\addons\script.module.urllib3\lib\urllib3\response.py", line 50, in decompress
             decompressed = self._obj.decompress(data)
         zlib.error: Error -3 while decompressing data: incorrect header check
```

The odd thing is that the player uses the exact same code as the rest of the add-on to authenticate with the Emby server.

**Comment by sualfred** [comment]
As discussed on Slack this is a Kodi issue in general with Exception name handlings. 
`except Foo:` is sometimes not recognized. Only `except:` will work in this case. 
The others are looking into it.
