### ISSUE TITLE
Exception and broken sync after item deletion on the server

### ISSUE THREAD

**Issue by sualfred** [Montellese/mediaimporter.emby#32]
Already reported on Slack.

To reproduce:

- Close Kodi
- Delete a series on the server
- Start Kodi and let the fast sync kick in

Exception:
```
2020-05-12 11:34:59.050 T:52696    INFO <general>: [mediaimporter.emby] Emby Media Import importer started
2020-05-12 11:34:59.051 T:52696    INFO <general>: [mediaimporter.emby] importing ['tvshow', 'season', 'episode'] items from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)...
2020-05-12 11:34:59.072 T:52696    INFO <general>: [mediaimporter.emby] importing tvshow items from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)...
2020-05-12 11:34:59.072 T:52696    INFO <general>: [mediaimporter.emby] importing tvshow items from "Serien" view from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)...
2020-05-12 11:34:59.077 T:52696    INFO <general>: [mediaimporter.emby] importing tvshow items from "HDR Serien" view from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)...
2020-05-12 11:34:59.089 T:52696    INFO <general>: [mediaimporter.emby] 1 previously imported tvshow items removed from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)
2020-05-12 11:34:59.095 T:52696   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmcmediaimport' has no attribute 'MediaImportChangesetTypeRemoved'
                                                   Traceback (most recent call last):
                                                     File "E:\Kodi\Kodi Media Import\portable_data\addons\mediaimporter.emby\importer.py", line 17, in <module>
                                                       importer.run(sys.argv)
                                                     File "E:\Kodi\Kodi Media Import\portable_data\addons\mediaimporter.emby\lib\importer.py", line 986, in run
                                                       actionMethod(handle, options)
                                                     File "E:\Kodi\Kodi Media Import\portable_data\addons\mediaimporter.emby\lib\importer.py", line 819, in execImport
                                                       xbmcmediaimport.MediaImportChangesetTypeRemoved)
                                                   AttributeError: module 'xbmcmediaimport' has no attribute 'MediaImportChangesetTypeRemoved'
                                                   -->End of Python script error report<--
                                                   
```

**Comment by Montellese** [comment]
I've seen this problem once as well but with the `MediaImportChangesetTypeAdded` constant. But then I rebuilt the python bindings and made the same changes and it worked the second time. That's why I assumed something was wrong with my build at the time.

I changed something around these constants before the latest test build though so maybe something went wrong there.

Can you reproduce this consistently?
