### ISSUE TITLE
Emby Media Importer Error: 'isDefault' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by rahaaatul** [Montellese/mediaimporter.emby#43]
```java
2023-07-18 15:38:58.061 T:11112    info <general>: [mediaimporter.emby] Emby Media Import importer started
2023-07-18 15:39:06.488 T:10100    info <general>: [mediaimporter.emby] [observer] processing userdata changed message from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/)...
2023-07-18 15:39:06.510 T:10100 warning <general>: [mediaimporter.emby] [observer] unknown exception when receiving data from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/): Unknown string format: %s
2023-07-18 15:39:08.383 T:6292     info <general>: CActiveAESink::OpenSink - initialize sink
2023-07-18 15:39:14.941 T:9964     info <general>: [mediaimporter.emby] Emby Media Import importer started
2023-07-18 15:39:22.549 T:13244    info <CGUIDialogMediaImportInfo>: Skipped 1 duplicate messages..
2023-07-18 15:39:22.549 T:13244    info <CGUIDialogMediaImportInfo>: settings for import "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set] saved
2023-07-18 15:39:22.625 T:10100    info <general>: [mediaimporter.emby] [observer] media import "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) ['movie', 'set'] from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) updated
2023-07-18 15:39:24.886 T:13244    info <CMediaImportManager>: import task for "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set] started
2023-07-18 15:39:24.886 T:14040    info <CMediaImportItemsSynchronizationJob>: starting local items retrieval task for items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set]...
2023-07-18 15:39:24.910 T:14040    info <CMediaImportItemsSynchronizationJob>: starting import items retrieval task for items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set]...
2023-07-18 15:39:25.236 T:4976     info <general>: [mediaimporter.emby] Emby Media Import importer started
2023-07-18 15:39:25.238 T:4976     info <general>: [mediaimporter.emby] importing ['movie', 'set'] items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/)...
2023-07-18 15:39:26.318 T:4976     info <general>: [mediaimporter.emby] forcing a full synchronization to import ['movie', 'set'] items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) because some related settings have changed
2023-07-18 15:39:26.318 T:4976     info <general>: [mediaimporter.emby] importing movie items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/)...
2023-07-18 15:39:32.315 T:4976    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'isDefault' is an invalid keyword argument for this function
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Administrator\Desktop\Kodi\portable_data\addons\mediaimporter.emby\importer.py", line 17, in <module>
                                                       importer.run(sys.argv)
                                                     File "C:\Users\Administrator\Desktop\Kodi\portable_data\addons\mediaimporter.emby\lib\importer.py", line 1160, in run
                                                       actionMethod(handle, options)
                                                     File "C:\Users\Administrator\Desktop\Kodi\portable_data\addons\mediaimporter.emby\lib\importer.py", line 941, in execImport
                                                       boxsetItems = importItems(handle, embyServer, url, mediaType, boxsetId,
                                                     File "C:\Users\Administrator\Desktop\Kodi\portable_data\addons\mediaimporter.emby\lib\importer.py", line 594, in importItems
                                                       for importedItems in gen:
                                                     File "C:\Users\Administrator\Desktop\Kodi\portable_data\addons\mediaimporter.emby\lib\importer.py", line 569, in importItemsGenerator
                                                       importItemsChunked(handle, embyServer, url, mediaType, viewId, startIndex, ITEM_REQUEST_LIMIT,
                                                     File "C:\Users\Administrator\Desktop\Kodi\portable_data\addons\mediaimporter.emby\lib\importer.py", line 547, in importItemsChunked
                                                       item = kodi.Api.toFileItem(embyServer, rawItem, mediaType, embyMediaType, viewName,
                                                     File "C:\Users\Administrator\Desktop\Kodi\portable_data\addons\mediaimporter.emby\lib\kodi.py", line 262, in toFileItem
                                                       item = Api.createVideoInfoItemWithVideoSetters(
                                                     File "C:\Users\Administrator\Desktop\Kodi\portable_data\addons\mediaimporter.emby\lib\kodi.py", line 451, in createVideoInfoItemWithVideoSetters
                                                       videoInfoTag.setRating(defaultRating, isDefault=True)
                                                   TypeError: 'isDefault' is an invalid keyword argument for this function
                                                   -->End of Python script error report<--
                                                   
2023-07-18 15:39:32.397 T:14040 warning <CMediaImportItemsSynchronizationJob>: import items retrieval task for items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set] failed
2023-07-18 15:39:32.397 T:14040    info <CMediaImportItemsSynchronizationJob>: starting import changeset task for movie items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set]...
2023-07-18 15:39:32.397 T:14040    info <CMediaImportItemsSynchronizationJob>: starting import changeset task for set items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set]...
2023-07-18 15:39:32.397 T:14040    info <CMediaImportItemsSynchronizationJob>: starting import synchronisation task for movie items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set]...
2023-07-18 15:39:32.397 T:14040    info <CMediaImportItemsSynchronizationJob>: starting import synchronisation task for set items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set]...
2023-07-18 15:39:32.408 T:14040    info <CMediaImportItemsSynchronizationJob>: starting import cleanup task for set items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set]...
2023-07-18 15:39:32.408 T:14040    info <CMediaImportCleanupTask>: cleaning up imported set items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/)
2023-07-18 15:39:32.414 T:14040    info <CMediaImportItemsSynchronizationJob>: starting import cleanup task for movie items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) [movie, set]...
2023-07-18 15:39:32.414 T:14040    info <CMediaImportCleanupTask>: cleaning up imported movie items from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/)
2023-07-18 15:39:32.625 T:10100    info <general>: [mediaimporter.emby] [observer] media import "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) ['movie', 'set'] from "billing" (emby://6aaad2ebfef9449f9d0c87f4f63ce181/) updated
```

**Comment by rahaaatul** [comment]
[Debug Log](https://paste.kodi.tv/isafivodes.kodi)

**Comment by Montellese** [comment]
This has already been fixed yesterday in `master`.

**Comment by rahaaatul** [comment]
> This has already been fixed yesterday in `master`.

I downloaded master as zip file, installed as zip file over the previous one, installed from the repository, and ran it again. 

And still I'm facing the same problem. Didn't I do it correctly?

**Comment by rahaaatul** [comment]
@Montellese Can we not sync the media without the watch status?

**Comment by Montellese** [comment]
@rahaaatul @Long-Man has already confirmed that the fix is working so you must have done something wrong during the installation process. You need to download the ZIP and then install the add-on in Kodi from the ZIP file. Don't install it from the repository afterwards or you will overwrite the ZIP version again.

**Comment by rahaaatul** [comment]
> You need to download the ZIP and then install the add-on in Kodi from the ZIP file. Don't install it from the repository afterwards or you will overwrite the ZIP version again.

I did exactly that @Montellese , that's why I got the problem. Now, the problem is gone.

By the way, would you answer this question, please? 
> Can we not sync the media without the watch status?

Because I disabled the settings and it still synced the watch status.

**Comment by Montellese** [comment]
> By the way, would you answer this question, please?
> 
> > Can we not sync the media without the watch status?
> 
> Because I disabled the settings and it still synced the watch status.

I'll take a look at that.

**Comment by Long-Man** [comment]
He wanted to not import

- Watch status
- Playcount
- Resume point
Commenting out the following from kodi.py achieved the desired result for him. I not sure if that is the best place to do it. However, I didn't want to bug you so I suggested that and it worked for him.
```
videoInfoTag.setPlaycount(userdata.get(constants.PROPERTY_ITEM_USER_DATA_PLAY_COUNT, 0)
                                  if userdata.get(constants.PROPERTY_ITEM_USER_DATA_PLAYED, False) else 0)
        videoInfoTag.setLastPlayed(Api.convertDateTimeToDbDateTime(
                userdata.get(constants.PROPERTY_ITEM_USER_DATA_LAST_PLAYED_DATE, '')))
```
```
# handle resume point
        videoInfoTag.setResumePoint(
            Api.ticksToSeconds(userdata.get(constants.PROPERTY_ITEM_USER_DATA_PLAYBACK_POSITION_TICKS, 0)),
            duration
            )
```
